id: AB3AA77A4
base_file: fF107.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 23:16:19.244805
  last_modified_at: 2022-05-30 23:16:19.244814
